"""initial_schema

Revision ID: 46cca3d1ba97
Revises:
Create Date: 2026-09-28 00:33:16.995410
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46cca3d1ba97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_slug'), ['slug'], unique=True)

    op.create_table('brand_profile_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=300), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', 'version', name='uq_brand_version')
    )
    with op.batch_alter_table('brand_profile_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_profile_versions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('source_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('rights_status', sa.String(length=30), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('media_path', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'sha256', 'title', name='uq_source_hash_title')
    )
    with op.batch_alter_table('source_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_assets_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_assets_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workflow_incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('operation_key', sa.String(length=180), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'operation_key', name='uq_incident_operation')
    )
    with op.batch_alter_table('workflow_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_incidents_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('login_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('transcript_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source_asset_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.String(length=35), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_asset_id'], ['source_assets.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_asset_id', 'version', name='uq_transcript_version')
    )
    with op.batch_alter_table('transcript_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_versions_source_asset_id'), ['source_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_versions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('content_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source_asset_id', sa.String(length=36), nullable=False),
    sa.Column('transcript_version_id', sa.String(length=36), nullable=True),
    sa.Column('brand_profile_version_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_version', sa.String(length=40), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_profile_version_id'], ['brand_profile_versions.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['source_assets.id'], ),
    sa.ForeignKeyConstraint(['transcript_version_id'], ['transcript_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'source_hash', 'recipe_version', 'brand_profile_version_id', name='uq_batch_recipe')
    )
    with op.batch_alter_table('content_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_batches_source_asset_id'), ['source_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_batches_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stable_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('transcript_version_id', sa.String(length=36), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_version_id'], ['transcript_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_version_id', 'stable_id', name='uq_segment_stable')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_stable_id'), ['stable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_transcript_version_id'), ['transcript_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_segment_ids', sa.JSON(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['content_batches.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('content_asset_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('logical_asset_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('slides_json', sa.JSON(), nullable=False),
    sa.Column('clip_range_json', sa.JSON(), nullable=True),
    sa.Column('source_segment_ids', sa.JSON(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('render_urls_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['content_batches.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_asset_id', 'version', name='uq_asset_version')
    )
    with op.batch_alter_table('content_asset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_asset_versions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_asset_versions_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_asset_versions_logical_asset_id'), ['logical_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_asset_versions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=180), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['content_batches.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'event_id', name='uq_webhook_event')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('dispatch_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('operation_key', sa.String(length=180), nullable=False),
    sa.Column('asset_version_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['content_asset_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'operation_key', name='uq_dispatch_operation')
    )
    with op.batch_alter_table('dispatch_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_ledger_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('asset_version_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['content_asset_versions.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['content_batches.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('publication_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('asset_version_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['content_asset_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publication_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_drafts_asset_version_id'), ['asset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_drafts_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('asset_version_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('expected_hash', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['content_asset_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_version_id', name='uq_review_once')
    )
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_decisions_asset_version_id'), ['asset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_decisions_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_decisions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_review_decisions_asset_version_id'))

    op.drop_table('review_decisions')
    with op.batch_alter_table('publication_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_drafts_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_publication_drafts_asset_version_id'))

    op.drop_table('publication_drafts')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_workspace_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('dispatch_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_ledger_workspace_id'))

    op.drop_table('dispatch_ledger')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_workspace_id'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('content_asset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_asset_versions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_content_asset_versions_logical_asset_id'))
        batch_op.drop_index(batch_op.f('ix_content_asset_versions_is_current'))
        batch_op.drop_index(batch_op.f('ix_content_asset_versions_batch_id'))

    op.drop_table('content_asset_versions')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_claims_batch_id'))

    op.drop_table('claims')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_segments_transcript_version_id'))
        batch_op.drop_index(batch_op.f('ix_segments_stable_id'))

    op.drop_table('segments')
    with op.batch_alter_table('content_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_batches_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_content_batches_source_asset_id'))

    op.drop_table('content_batches')
    with op.batch_alter_table('transcript_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_versions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_versions_source_asset_id'))

    op.drop_table('transcript_versions')
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_sessions_user_id'))

    op.drop_table('login_sessions')
    with op.batch_alter_table('workflow_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_incidents_workspace_id'))

    op.drop_table('workflow_incidents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_workspace_id'))

    op.drop_table('users')
    with op.batch_alter_table('source_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_assets_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_source_assets_sha256'))

    op.drop_table('source_assets')
    with op.batch_alter_table('brand_profile_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_profile_versions_workspace_id'))

    op.drop_table('brand_profile_versions')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_slug'))

    op.drop_table('workspaces')
    # ### end Alembic commands ###
